# Setup
title:               نفوذ
tagline:             'مجله هک و امنیت'
description:         'نفوذ'
url:                 https://nofoz.ir
baseurl:             '/'
paginate:            1
permalink:           /:title/

# About/contact
author:
  name:              Arya Mehralian
  url:               https://twitter.com/1
  email:             1@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
